### ISSUE TITLE
Feature Request : add additional fields to @Sample annotation

### ISSUE THREAD

**Issue by workspace** [google/casa-android#5]
Hello. I am interested in this project and would like to request some new features. (I had a similar idea to this project before!)

<img width="353" alt="image" src="https://user-images.githubusercontent.com/7759511/208868481-45bd3a04-954b-4afa-86e2-6e14e4a2c66b.png">

That is adding several fields to `@Sample` annotation. I would like to add `tags` and `author` fields. 
- `tags` field can provide more flexible classification than the current path-based filter. 
- `author` field can be used to show who proposed the Sample code, such as an email address or github username.

I'd like to make PR for this suggestion, however, I don't know the exact way to contribute.

> In ReadMe.md -> Contribution is allowed for anyone
> Please contribute! We will gladly review any pull requests. Make sure to read the [Contributing](https://github.com/google/casa-android/blob/main/CONTRIBUTING.md) page first though.
>
> In CONTRIBUTING.md -> Start a discussion via Github issues first
> Before contributing large new features and/or libraries please start a discussion with us first via GitHub Issues and check that we can support it. We are unable to support all new features, even though we wish we could! If we are unable to support adding your feature, we always encourage you to open source it in your own repository to help the Compose community grow.

**Comment by marcelpinto** [comment]
Thanks for proposing this. 

The idea to use the path-based filter was to simplify creation but I think optional tags would be a great addition. 
Instead of `author` I think a list of `owners` would be better, but it should also be optional.

To contribute, create a fork, do your changes and submit a new PR. Then make sure you have signed the CLA - https://cla.developers.google.com/clas

**Comment by workspace** [comment]
@marcelpinto Submit #6 to close this issue! Thanks for accepting my proposal.
